# Generated by Django 5.2.4 on 2025-07-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0002_pandingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Title', models.CharField(max_length=100, null=True)),
                ('course_duration', models.CharField(max_length=10, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_fee', models.PositiveIntegerField(null=True)),
                ('assign_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to='auth_user.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdmittedcourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_fee', models.PositiveIntegerField(null=True)),
                ('payment', models.PositiveIntegerField(null=True)),
                ('due', models.PositiveIntegerField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_courses', to='auth_user.studentmodel')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_courses', to='courseApp.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='payment_historyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount_paid', models.PositiveIntegerField(null=True)),
                ('due', models.PositiveIntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='courseApp.coursemodel')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='auth_user.studentmodel')),
            ],
        ),
    ]
