# Generated by Django 5.2.4 on 2025-07-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_historymodel',
            name='student',
        ),
        migrations.AlterField(
            model_name='payment_historymodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='courseApp.admittedcoursemodel'),
        ),
    ]
